# Generated by Django 4.2.15 on 2024-08-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamapp', '0002_spamreport_count_spam_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamreport',
            name='reported_by',
        ),
    ]
