# Generated by Django 4.2.15 on 2024-08-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamapp', '0005_spamreport_count_spam_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamreport',
            name='count_spam_hits',
        ),
    ]
